name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:
  # Schedule the workflow to run every 8 hours
  schedule:
    - cron: '0 */8 * * *'

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        with:
          path: blog-astro

      - name: Checkout Obsidian Brain to source posts
        uses: actions/checkout@v4  
        with:
          repository: meadowingc/obsidian-brain
          path: obsidian-brain
          token: ${{ secrets.OBSIDIAN_ACCESS_TOKEN }}

      # list pwd and ls to debug
      - name: List files in the repository
        run: |
          echo "----- Current directory -----"
          pwd
          echo "----- List files -----"
          ls -a
          echo "----- List files in blog-astro -----"
          ls -a blog-astro
          echo "----- List files in obsidian-brain -----"
          ls -a obsidian-brain

      - name: Install deps
        run: |
          cd blog-astro
          npm install
          cd ..

      - name: Build the site
        uses: withastro/action@v2
        with:
          path: ./blog-astro
          # path: . # The root location of your Astro project inside the repository. (optional)
          # node-version: 20 # The specific version of Node that should be used to build your site. Defaults to 20. (optional)
          # package-manager: pnpm@latest # The Node package manager that should be used to install dependencies and build your site. Automatically detected based on your lockfile. (optional)

      - name: Fire webmentions
        run: |
          cd blog-astro
          npm run doWebmentions
          cd ..
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
